version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: python-magic
    versions:
    - 0.4.18
    - 0.4.21
  - dependency-name: pyais
    versions:
    - 1.3.0
    - 1.3.1
  - dependency-name: unidecode
    versions:
    - 1.1.2
