mid2isoCC = {
    "201": {"isoCC": "AL"},
    "202": {"isoCC": "AD"},
    "203": {"isoCC": "AT"},
    "204": {"isoCC": "PT-20"},
    "205": {"isoCC": "BE"},
    "206": {"isoCC": "BY"},
    "207": {"isoCC": "BG"},
    "208": {"isoCC": "VA"},
    "209": {"isoCC": "CY"},
    "210": {"isoCC": "CY"},
    "211": {"isoCC": "DE"},
    "212": {"isoCC": "CY"},
    "213": {"isoCC": "GE"},
    "214": {"isoCC": "MD"},
    "215": {"isoCC": "MT"},
    "216": {"isoCC": "AM"},
    "218": {"isoCC": "DE"},
    "219": {"isoCC": "DK"},
    "220": {"isoCC": "DK"},
    "224": {"isoCC": "ES"},
    "225": {"isoCC": "ES"},
    "226": {"isoCC": "FR"},
    "227": {"isoCC": "FR"},
    "228": {"isoCC": "FR"},
    "230": {"isoCC": "FI"},
    "231": {"isoCC": "FO"},
    "232": {"isoCC": "GB"},
    "233": {"isoCC": "GB"},
    "234": {"isoCC": "GB"},
    "235": {"isoCC": "GB"},
    "236": {"isoCC": "GI"},
    "237": {"isoCC": "GR"},
    "238": {"isoCC": "HR"},
    "239": {"isoCC": "GR"},
    "240": {"isoCC": "GR"},
    "241": {"isoCC": "GR"},
    "242": {"isoCC": "MA"},
    "243": {"isoCC": "HU"},
    "244": {"isoCC": "NL"},
    "245": {"isoCC": "NL"},
    "246": {"isoCC": "NL"},
    "247": {"isoCC": "IT"},
    "248": {"isoCC": "MT"},
    "249": {"isoCC": "MT"},
    "250": {"isoCC": "IE"},
    "251": {"isoCC": "IS"},
    "252": {"isoCC": "LI"},
    "253": {"isoCC": "LU"},
    "254": {"isoCC": "MC"},
    "255": {"isoCC": "PT-30"},
    "256": {"isoCC": "MT"},
    "257": {"isoCC": "NO"},
    "258": {"isoCC": "NO"},
    "259": {"isoCC": "NO"},
    "261": {"isoCC": "PL"},
    "262": {"isoCC": "ME"},
    "263": {"isoCC": "PT"},
    "264": {"isoCC": "RO"},
    "265": {"isoCC": "SE"},
    "266": {"isoCC": "SE"},
    "267": {"isoCC": "SK"},
    "268": {"isoCC": "SM"},
    "269": {"isoCC": "CH"},
    "270": {"isoCC": "CZ"},
    "271": {"isoCC": "TR"},
    "272": {"isoCC": "UA"},
    "273": {"isoCC": "RU"},
    "274": {"isoCC": "MK"},
    "275": {"isoCC": "LV"},
    "276": {"isoCC": "EE"},
    "277": {"isoCC": "LT"},
    "278": {"isoCC": "SI"},
    "279": {"isoCC": "RS"},
    "301": {"isoCC": "AI"},
    "303": {"isoCC": "US-AK"},
    "304": {"isoCC": "AG"},
    "305": {"isoCC": "AG"},
    "306": {"isoCC": "AN"},
    "307": {"isoCC": "NL-AW"},
    "308": {"isoCC": "BS"},
    "309": {"isoCC": "BS"},
    "310": {"isoCC": "BM"},
    "311": {"isoCC": "BS"},
    "312": {"isoCC": "BZ"},
    "314": {"isoCC": "BB"},
    "316": {"isoCC": "CA"},
    "319": {"isoCC": "KY"},
    "321": {"isoCC": "CR"},
    "323": {"isoCC": "CU"},
    "325": {"isoCC": "DM"},
    "327": {"isoCC": "DO"},
    "329": {"isoCC": "FR-GP"},
    "330": {"isoCC": "GD"},
    "331": {"isoCC": "GL"},
    "332": {"isoCC": "GT"},
    "334": {"isoCC": "HN"},
    "336": {"isoCC": "HT"},
    "338": {"isoCC": "US"},
    "339": {"isoCC": "JM"},
    "341": {"isoCC": "KN"},
    "343": {"isoCC": "LC"},
    "345": {"isoCC": "MX"},
    "347": {"isoCC": "FR-MQ"},
    "348": {"isoCC": "MS"},
    "350": {"isoCC": "NI"},
    "351": {"isoCC": "PA"},
    "352": {"isoCC": "PA"},
    "353": {"isoCC": "PA"},
    "354": {"isoCC": "PA"},
    "355": {"isoCC": "PA"},
    "356": {"isoCC": "PA"},
    "357": {"isoCC": "PA"},
    "358": {"isoCC": "US-PR"},
    "359": {"isoCC": "SV"},
    "361": {"isoCC": "FR-PM"},
    "362": {"isoCC": "TT"},
    "364": {"isoCC": "TC"},
    "366": {"isoCC": "US"},
    "367": {"isoCC": "US"},
    "368": {"isoCC": "US"},
    "369": {"isoCC": "US"},
    "370": {"isoCC": "PA"},
    "371": {"isoCC": "PA"},
    "372": {"isoCC": "PA"},
    "373": {"isoCC": "PA"},
    "374": {"isoCC": "PA"},
    "375": {"isoCC": "VC"},
    "376": {"isoCC": "VC"},
    "377": {"isoCC": "VC"},
    "378": {"isoCC": "VG"},
    "379": {"isoCC": "US-VI"},
    "401": {"isoCC": "AF"},
    "403": {"isoCC": "SA"},
    "405": {"isoCC": "BD"},
    "408": {"isoCC": "BH"},
    "410": {"isoCC": "BT"},
    "412": {"isoCC": "CN"},
    "413": {"isoCC": "CN"},
    "416": {"isoCC": "CN-TW"},
    "417": {"isoCC": "LK"},
    "419": {"isoCC": "IN"},
    "422": {"isoCC": "IR"},
    "423": {"isoCC": "AZ"},
    "425": {"isoCC": "IQ"},
    "428": {"isoCC": "IL"},
    "431": {"isoCC": "JP"},
    "432": {"isoCC": "JP"},
    "434": {"isoCC": "TM"},
    "436": {"isoCC": "KZ"},
    "437": {"isoCC": "UZ"},
    "438": {"isoCC": "JO"},
    "440": {"isoCC": "KR"},
    "441": {"isoCC": "KR"},
    "443": {"isoCC": "PS"},
    "445": {"isoCC": "KP"},
    "447": {"isoCC": "KW"},
    "450": {"isoCC": "LB"},
    "451": {"isoCC": "KG"},
    "453": {"isoCC": "CN-MO"},
    "455": {"isoCC": "MV"},
    "457": {"isoCC": "MN"},
    "459": {"isoCC": "NP"},
    "461": {"isoCC": "OM"},
    "463": {"isoCC": "PK"},
    "466": {"isoCC": "QA"},
    "468": {"isoCC": "SY"},
    "470": {"isoCC": "AE"},
    "473": {"isoCC": "YE"},
    "475": {"isoCC": "YE"},
    "477": {"isoCC": "CN-HK"},
    "478": {"isoCC": "BA"},
    "501": {"isoCC": "AQ"},
    "503": {"isoCC": "AU"},
    "506": {"isoCC": "MM"},
    "508": {"isoCC": "BN"},
    "510": {"isoCC": "FM"},
    "511": {"isoCC": "PW"},
    "512": {"isoCC": "NZ"},
    "514": {"isoCC": "KH"},
    "515": {"isoCC": "KH"},
    "516": {"isoCC": "CX"},
    "518": {"isoCC": "CK"},
    "520": {"isoCC": "FJ"},
    "523": {"isoCC": "CC"},
    "525": {"isoCC": "ID"},
    "529": {"isoCC": "KI"},
    "531": {"isoCC": "LA"},
    "533": {"isoCC": "MY"},
    "536": {"isoCC": "US-MP"},
    "538": {"isoCC": "MH"},
    "540": {"isoCC": "NC"},
    "542": {"isoCC": "NU"},
    "544": {"isoCC": "NR"},
    "546": {"isoCC": "FR-PF"},
    "548": {"isoCC": "PH"},
    "553": {"isoCC": "PG"},
    "555": {"isoCC": "PN"},
    "557": {"isoCC": "SB"},
    "559": {"isoCC": "US-AS"},
    "561": {"isoCC": "WS"},
    "563": {"isoCC": "SG"},
    "564": {"isoCC": "SG"},
    "565": {"isoCC": "SG"},
    "567": {"isoCC": "TH"},
    "570": {"isoCC": "TO"},
    "572": {"isoCC": "TV"},
    "574": {"isoCC": "VN"},
    "576": {"isoCC": "VU"},
    "578": {"isoCC": "FR-WF"},
    "601": {"isoCC": "ZA"},
    "603": {"isoCC": "AO"},
    "605": {"isoCC": "DZ"},
    "607": {"isoCC": "FR-TF"},
    "608": {"isoCC": "SH"},
    "609": {"isoCC": "BI"},
    "610": {"isoCC": "BJ"},
    "611": {"isoCC": "BW"},
    "612": {"isoCC": "CF"},
    "613": {"isoCC": "CM"},
    "615": {"isoCC": "CG"},
    "616": {"isoCC": "KM"},
    "617": {"isoCC": "CV"},
    "618": {"isoCC": "FR-TF"},
    "619": {"isoCC": "CI"},
    "621": {"isoCC": "DJ"},
    "622": {"isoCC": "EG"},
    "624": {"isoCC": "ET"},
    "625": {"isoCC": "ER"},
    "626": {"isoCC": "GA"},
    "627": {"isoCC": "GH"},
    "629": {"isoCC": "GM"},
    "630": {"isoCC": "GW"},
    "631": {"isoCC": "GQ"},
    "632": {"isoCC": "GN"},
    "633": {"isoCC": "BF"},
    "634": {"isoCC": "KE"},
    "635": {"isoCC": "FR-TF"},
    "636": {"isoCC": "LR"},
    "637": {"isoCC": "LR"},
    "642": {"isoCC": "LY"},
    "644": {"isoCC": "LS"},
    "645": {"isoCC": "MU"},
    "647": {"isoCC": "MG"},
    "649": {"isoCC": "ML"},
    "650": {"isoCC": "MZ"},
    "654": {"isoCC": "MR"},
    "655": {"isoCC": "MW"},
    "656": {"isoCC": "NE"},
    "657": {"isoCC": "NG"},
    "659": {"isoCC": "NA"},
    "660": {"isoCC": "FR-RE"},
    "661": {"isoCC": "RW"},
    "662": {"isoCC": "SS"},
    "663": {"isoCC": "SN"},
    "664": {"isoCC": "SC"},
    "665": {"isoCC": "SH"},
    "666": {"isoCC": "SO"},
    "667": {"isoCC": "SL"},
    "668": {"isoCC": "ST"},
    "669": {"isoCC": "SZ"},
    "670": {"isoCC": "TD"},
    "671": {"isoCC": "GB"},
    "672": {"isoCC": "TN"},
    "674": {"isoCC": "TZ"},
    "675": {"isoCC": "UG"},
    "676": {"isoCC": "CG"},
    "677": {"isoCC": "TZ"},
    "678": {"isoCC": "ZM"},
    "679": {"isoCC": "ZW"},
    "701": {"isoCC": "AR"},
    "710": {"isoCC": "BR"},
    "720": {"isoCC": "BO"},
    "725": {"isoCC": "CL"},
    "730": {"isoCC": "CO"},
    "735": {"isoCC": "EC"},
    "740": {"isoCC": "FK"},
    "745": {"isoCC": "FR-GF"},
    "750": {"isoCC": "GY"},
    "755": {"isoCC": "PY"},
    "760": {"isoCC": "PE"},
    "765": {"isoCC": "SR"},
    "770": {"isoCC": "UR"},
    "775": {"isoCC": "VE"},
}

isoCC2country = {
    "AD": {"country": "Andorra (Principality of)"},
    "AE": {"country": "United Arab Emirates"},
    "AF": {"country": "Afghanistan"},
    "AG": {"country": "Antigua and Barbuda"},
    "AI": {"country": "Anguilla"},
    "AL": {"country": "Albania (Republic of)"},
    "AM": {"country": "Armenia (Republic of)"},
    "AN": {"country": "Netherlands Antilles"},
    "AO": {"country": "Angola (Republic of)"},
    "AQ": {"country": "Adelie Land"},
    "AR": {"country": "Argentine Republic"},
    "AT": {"country": "Austria"},
    "AU": {"country": "Australia"},
    "AZ": {"country": "Azerbaijani Republic"},
    "BA": {"country": "Bosnia and Herzegovina"},
    "BB": {"country": "Barbados"},
    "BD": {"country": "Bangladesh (People's Republic of)"},
    "BE": {"country": "Belgium"},
    "BF": {"country": "Burkina Faso"},
    "BG": {"country": "Bulgaria (Republic of)"},
    "BH": {"country": "Bahrain (Kingdom of)"},
    "BI": {"country": "Burundi (Republic of)"},
    "BJ": {"country": "Benin (Republic of)"},
    "BM": {"country": "Bermuda"},
    "BN": {"country": "Brunei Darussalam"},
    "BO": {"country": "Bolivia (Plurinational State of)"},
    "BR": {"country": "Brazil (Federative Republic of)"},
    "BS": {"country": "Bahamas (Commonwealth of the)"},
    "BT": {"country": "Bhutan (Kingdom of)"},
    "BW": {"country": "Botswana (Republic of)"},
    "BY": {"country": "Belarus (Republic of)"},
    "BZ": {"country": "Belize"},
    "CA": {"country": "Canada"},
    "CC": {"country": "Cocos (Keeling) Islands"},
    "CF": {"country": "Central African Republic"},
    "CG": {"country": "Congo (Republic of the)"},
    "CG": {"country": "Democratic Republic of the Congo"},
    "CH": {"country": "Switzerland (Confederation of)"},
    "CI": {"country": "Cote d'Ivoire (Republic of)"},
    "CK": {"country": "Cook Islands"},
    "CL": {"country": "Chile"},
    "CM": {"country": "Cameroon (Republic of)"},
    "CN": {"country": "China (People's Republic of)"},
    "CN-HK": {"country": "Hong Kong (Special Administrative Region of China)"},
    "CN-MO": {"country": "Macao (Special Administrative Region of China)"},
    "CN-TW": {"country": "Taiwan (Province of China)"},
    "CO": {"country": "Colombia (Republic of)"},
    "CR": {"country": "Costa Rica"},
    "CU": {"country": "Cuba"},
    "CV": {"country": "Cape Verde (Republic of)"},
    "CX": {"country": "Christmas Island (Indian Ocean)"},
    "CY": {"country": "Cyprus (Republic of)"},
    "CZ": {"country": "Czech Republic"},
    "DE": {"country": "Germany (Federal Republic of)"},
    "DJ": {"country": "Djibouti (Republic of)"},
    "DK": {"country": "Denmark"},
    "DM": {"country": "Dominica (Commonwealth of)"},
    "DO": {"country": "Dominican Republic"},
    "DZ": {"country": "Algeria (People's Democratic Republic of)"},
    "EC": {"country": "Ecuador"},
    "EE": {"country": "Estonia (Republic of)"},
    "EG": {"country": "Egypt (Arab Republic of)"},
    "ER": {"country": "Eritrea"},
    "ES": {"country": "Spain"},
    "ET": {"country": "Ethiopia (Federal Democratic Republic of)"},
    "FI": {"country": "Finland"},
    "FJ": {"country": "Fiji (Republic of)"},
    "FK": {"country": "Falkland Islands (Malvinas)"},
    "FM": {"country": "Micronesia (Federated States of)"},
    "FO": {"country": "Faroe Islands"},
    "FR": {"country": "France"},
    "FR-GF": {"country": "Guiana (French Department of)"},
    "FR-GP": {"country": "Guadeloupe (French Department of)"},
    "FR-MQ": {"country": "Martinique (French Department of)"},
    "FR-PF": {"country": "French Polynesia"},
    "FR-PM": {"country": "Saint Pierre and Miquelon (Territorial Collectivity of)"},
    "FR-RE": {"country": "Reunion (French Department of)"},
    "FR-TF": {"country": "Crozet Archipelago"},
    "FR-TF": {"country": "Kerguelen Islands"},
    "FR-TF": {"country": "Saint Paul and Amsterdam Islands"},
    "FR-WF": {"country": "Wallis and Futuna Islands"},
    "GA": {"country": "Gabonese Republic"},
    "GB": {"country": "Togolese Republic"},
    "GB": {"country": "United Kingdom of Great Britain and Northern Ireland"},
    "GD": {"country": "Grenada"},
    "GE": {"country": "Georgia"},
    "GH": {"country": "Ghana"},
    "GI": {"country": "Gibraltar"},
    "GL": {"country": "Greenland"},
    "GM": {"country": "Gambia (Republic of the)"},
    "GN": {"country": "Guinea (Republic of)"},
    "GQ": {"country": "Equatorial Guinea (Republic of)"},
    "GR": {"country": "Greece"},
    "GT": {"country": "Guatemala (Republic of)"},
    "GW": {"country": "Guinea-Bissau (Republic of)"},
    "GY": {"country": "Guyana"},
    "HN": {"country": "Honduras (Republic of)"},
    "HR": {"country": "Croatia (Republic of)"},
    "HT": {"country": "Haiti (Republic of)"},
    "ID": {"country": "Indonesia (Republic of)"},
    "IS": {"country": "Iceland"},
    "IE": {"country": "Ireland"},
    "IL": {"country": "Israel (State of)"},
    "IN": {"country": "India (Republic of)"},
    "IQ": {"country": "Iraq (Republic of)"},
    "IR": {"country": "Iran (Islamic Republic of)"},
    "IT": {"country": "Italy"},
    "JM": {"country": "Jamaica"},
    "JO": {"country": "Jordan (Hashemite Kingdom of)"},
    "JP": {"country": "Japan"},
    "KE": {"country": "Kenya (Republic of)"},
    "KG": {"country": "Kyrgyz Republic"},
    "KH": {"country": "Cambodia (Kingdom of)"},
    "KI": {"country": "Kiribati (Republic of)"},
    "KM": {"country": "Comoros (Union of the)"},
    "KN": {"country": "Saint Kitts and Nevis (Federation of)"},
    "KP": {"country": "Democratic People's Republic of Korea"},
    "KR": {"country": "Korea (Republic of)"},
    "KW": {"country": "Kuwait (State of)"},
    "KY": {"country": "Cayman Islands"},
    "KZ": {"country": "Kazakhstan (Republic of)"},
    "LA": {"country": "Lao People's Democratic Republic"},
    "LB": {"country": "Lebanon"},
    "LC": {"country": "Saint Lucia"},
    "LI": {"country": "Liechtenstein (Principality of)"},
    "LK": {"country": "Sri Lanka (Democratic Socialist Republic of)"},
    "LR": {"country": "Liberia (Republic of)"},
    "LS": {"country": "Lesotho (Kingdom of)"},
    "LT": {"country": "Lithuania (Republic of)"},
    "LU": {"country": "Luxembourg"},
    "LV": {"country": "Latvia (Republic of)"},
    "LY": {"country": "Socialist People's Libyan Arab Jamahiriya"},
    "MA": {"country": "Morocco (Kingdom of)"},
    "MC": {"country": "Monaco (Principality of)"},
    "MD": {"country": "Moldova (Republic of)"},
    "ME": {"country": "Montenegro"},
    "MG": {"country": "Madagascar (Republic of)"},
    "MH": {"country": "Marshall Islands (Republic of the)"},
    "MK": {"country": "The Former Yugoslav Republic of Macedonia"},
    "ML": {"country": "Mali (Republic of)"},
    "MM": {"country": "Myanmar (Union of)"},
    "MN": {"country": "Mongolia"},
    "MR": {"country": "Mauritania (Islamic Republic of)"},
    "MS": {"country": "Montserrat"},
    "MT": {"country": "Malta"},
    "MU": {"country": "Mauritius (Republic of)"},
    "MV": {"country": "Maldives (Republic of)"},
    "MW": {"country": "Malawi"},
    "MX": {"country": "Mexico"},
    "MY": {"country": "Malaysia"},
    "MZ": {"country": "Mozambique (Republic of)"},
    "NA": {"country": "Namibia (Republic of)"},
    "NC": {"country": "New Caledonia"},
    "NE": {"country": "Niger (Republic of the)"},
    "NG": {"country": "Nigeria (Federal Republic of)"},
    "NI": {"country": "Nicaragua"},
    "NL-AW": {"country": "Aruba"},
    "NL": {"country": "Netherlands (Kingdom of the)"},
    "NO": {"country": "Norway"},
    "NP": {"country": "Nepal (Federal Democratic Republic of)"},
    "NR": {"country": "Nauru (Republic of)"},
    "NU": {"country": "Niue"},
    "NZ": {"country": "New Zealand"},
    "OM": {"country": "Oman (Sultanate of)"},
    "PA": {"country": "Panama (Republic of)"},
    "PE": {"country": "Peru"},
    "PG": {"country": "Papua New Guinea"},
    "PH": {"country": "Philippines (Republic of the)"},
    "PK": {"country": "Pakistan (Islamic Republic of)"},
    "PL": {"country": "Poland (Republic of)"},
    "PN": {"country": "Pitcairn Island"},
    "PS": {"country": "Palestine (In accordance with Resolution 99 Rev. Antalya 2006)"},
    "PT-20": {"country": "Azores"},
    "PT-30": {"country": "Madeira"},
    "PT": {"country": "Portugal"},
    "PW": {"country": "Palau (Republic of)"},
    "PY": {"country": "Paraguay (Republic of)"},
    "QA": {"country": "Qatar (State of)"},
    "RO": {"country": "Romania"},
    "RS": {"country": "Serbia (Republic of)"},
    "RU": {"country": "Russian Federation"},
    "RW": {"country": "Rwanda (Republic of)"},
    "SA": {"country": "Saudi Arabia (Kingdom of)"},
    "SB": {"country": "Solomon Islands"},
    "SC": {"country": "Seychelles (Republic of)"},
    "SE": {"country": "Sweden"},
    "SG": {"country": "Singapore (Republic of)"},
    "SH": {"country": "Ascension Island"},
    "SH": {"country": "Saint Helena"},
    "SI": {"country": "Slovenia (Republic of)"},
    "SK": {"country": "Slovak Republic"},
    "SL": {"country": "Sierra Leone"},
    "SM": {"country": "San Marino (Republic of)"},
    "SN": {"country": "Senegal (Republic of)"},
    "SO": {"country": "Somali Democratic Republic"},
    "SR": {"country": "Suriname (Republic of)"},
    "SS": {"country": "Sudan (Republic of the)"},
    "ST": {"country": "Sao Tome and Principe (Democratic Republic of)"},
    "SV": {"country": "El Salvador (Republic of)"},
    "SY": {"country": "Syrian Arab Republic"},
    "SZ": {"country": "Swaziland (Kingdom of)"},
    "TC": {"country": "Turks and Caicos Islands"},
    "TD": {"country": "Chad (Republic of)"},
    "TH": {"country": "Thailand"},
    "TJ": {"country": "Tajikistan"},
    "TM": {"country": "Turkmenistan"},
    "TN": {"country": "Tunisia"},
    "TO": {"country": "Tonga (Kingdom of)"},
    "TR": {"country": "Turkey"},
    "TT": {"country": "Trinidad and Tobago"},
    "TV": {"country": "Tuvalu"},
    "TZ": {"country": "Tanzania (United Republic of)"},
    "UA": {"country": "Ukraine"},
    "UG": {"country": "Uganda (Republic of)"},
    "HU": {"country": "Hungary (Republic of)"},
    "UR": {"country": "Uruguay (Eastern Republic of)"},
    "US-AK": {"country": "Alaska (State of)"},
    "US-AS": {"country": "American Samoa"},
    "US": {"country": "United States of America"},
    "US-MP": {"country": "Northern Mariana Islands (Commonwealth of the)"},
    "US-PR": {"country": "Puerto Rico"},
    "US-VI": {"country": "United States Virgin Islands"},
    "UZ": {"country": "Uzbekistan (Republic of)"},
    "VA": {"country": "Vatican City State"},
    "VC": {"country": "Saint Vincent and the Grenadines"},
    "VE": {"country": "Venezuela (Bolivarian Republic of)"},
    "VG": {"country": "British Virgin Islands"},
    "VN": {"country": "Viet Nam (Socialist Republic of)"},
    "VU": {"country": "Vanuatu (Republic of)"},
    "WS": {"country": "Samoa (Independent State of)"},
    "YE": {"country": "Yemen (Republic of)"},
    "YU": {"country": "Yugoslavia"},
    "ZA": {"country": "South Africa (Republic of)"},
    "ZM": {"country": "Zambia (Republic of)"},
    "ZW": {"country": "Zimbabwe (Republic of)"},
}
