defmodule Mix.Tasks.Pyairwaves.UpdateAircraftsRegistrations do
  use Mix.Task
  import Mix.Tasks.Pyairwaves

  require Logger

  @moduledoc """
  Update the list of known aircrafts registrations

  Cron recommanded: none. Only run at install.
  """

  @shortdoc "Update the list of known aircrafts registrations"
  def run(_) do
    # start the required apps & repos
    start_apps()

    Logger.info("Starting aircraft registrations update. (Offline)")
    Logger.info("This can take some time.")

    Pyairwaves.Repo.delete_all(Pyairwaves.AircraftRegistration)
    Logger.info("Table cleaned.")

    regs = registrations()
    Pyairwaves.Repo.insert_all(Pyairwaves.AircraftRegistration, regs, on_conflict: :nothing, log: false)

    Logger.info("Update finished, handled #{length(regs)} items.")
  end

  defp registrations do
    [
      %{country: "Afghanistan", prefix: "YA"},
      %{country: "Albania", prefix: "ZA"},
      %{country: "Algeria", prefix: "7T"},
      %{country: "Andorra", prefix: "C3"},
      %{country: "Angola", prefix: "D2"},
      %{country: "Anguilla", prefix: "VP"},
      %{country: "Antigua and Barbuda", prefix: "V2"},
      %{country: "Argentina", prefix: "LV"},
      %{country: "Argentina", prefix: "LQ"},
      %{country: "Armenia", prefix: "EK"},
      %{country: "Aruba", prefix: "P4"},
      %{country: "Australia", prefix: "VH"},
      %{country: "Austria", prefix: "OE"},
      %{country: "Azerbaijan", prefix: "4K"},
      %{country: "Bahamas", prefix: "C6"},
      %{country: "Bahrain", prefix: "A9C"},
      %{country: "Bangladesh", prefix: "S2"},
      %{country: "Barbados", prefix: "8P"},
      %{country: "Belarus", prefix: "EW"},
      %{country: "Belgium", prefix: "OO"},
      %{country: "Belize", prefix: "V3"},
      %{country: "Benin", prefix: "TY"},
      %{country: "Bermuda", prefix: "VP"},
      %{country: "Bermuda", prefix: "VQ"},
      %{country: "Bhutan", prefix: "A5"},
      %{country: "Bolivia", prefix: "CP"},
      %{country: "Bosnia and Herzegovina", prefix: "T9"},
      %{country: "Bosnia and Herzegovina", prefix: "E7"},
      %{country: "Botswana", prefix: "A2"},
      %{country: "Brazil", prefix: "PP"},
      %{country: "Brazil", prefix: "PR"},
      %{country: "Brazil", prefix: "PT"},
      %{country: "Brazil", prefix: "PU"},
      %{country: "British Virgin Islands", prefix: "VP"},
      %{country: "Brunei", prefix: "V8"},
      %{country: "Bulgaria", prefix: "LZ"},
      %{country: "Burkina Faso", prefix: "XT"},
      %{country: "Burundi", prefix: "9U"},
      %{country: "Cambodia", prefix: "XU"},
      %{country: "Cameroon", prefix: "TJ"},
      %{country: "Canada", prefix: "C"},
      %{country: "Cape Verde", prefix: "D4"},
      %{country: "Cayman Islands", prefix: "VP"},
      %{country: "Central African Republic", prefix: "TL"},
      %{country: "Chad", prefix: "TT"},
      %{country: "Chile", prefix: "CC"},
      %{country: "Republic of China (Taiwan)", prefix: "B"},
      %{country: "People's Republic of China", prefix: "B"},
      %{country: "Hong Kong", prefix: "B"},
      %{country: "Macau,China", prefix: "B"},
      %{country: "Colombia", prefix: "HU"},
      %{country: "Colombia", prefix: "HK"},
      %{country: "Comoros", prefix: "D6"},
      %{country: "Congo,Republic of", prefix: "TN"},
      %{country: "Cook Islands", prefix: "E5"},
      %{country: "Congo,Democratic Republic of", prefix: "9Q"},
      %{country: "Costa Rica", prefix: "TI"},
      %{country: "Côte d'Ivoire", prefix: "TU"},
      %{country: "Croatia", prefix: "9A"},
      %{country: "Cuba", prefix: "CU"},
      %{country: "Cyprus,Republic of", prefix: "5B"},
      %{country: "Czech Republic", prefix: "OK"},
      %{country: "Denmark", prefix: "OY"},
      %{country: "Djibouti", prefix: "J2"},
      %{country: "Dominica", prefix: "J7"},
      %{country: "Dominican Republic", prefix: "HI"},
      %{country: "East Timor", prefix: "4W"},
      %{country: "East Timor", prefix: "N1"},
      %{country: "Ecuador", prefix: "HC"},
      %{country: "Egypt", prefix: "SU"},
      %{country: "El Salvador", prefix: "YS"},
      %{country: "Equatorial Guinea", prefix: "3C"},
      %{country: "Eritrea", prefix: "E3"},
      %{country: "Estonia", prefix: "ES"},
      %{country: "Ethiopia", prefix: "ET"},
      %{country: "Falkland Islands", prefix: "VP"},
      %{country: "Fiji Islands", prefix: "DQ"},
      %{country: "Finland", prefix: "OH"},
      %{country: "France", prefix: "F"},
      %{country: "French West Indies", prefix: "F"},
      %{country: "French Guyana", prefix: "F"},
      %{country: "Gabon", prefix: "TR"},
      %{country: "Gambia", prefix: "C5"},
      %{country: "Georgia", prefix: "4L"},
      %{country: "Germany", prefix: "D"},
      %{country: "Ghana", prefix: "9G"},
      %{country: "Gibraltar", prefix: "VP"},
      %{country: "Greece", prefix: "SX"},
      %{country: "Grenada", prefix: "J3"},
      %{country: "Guatemala", prefix: "TG"},
      %{country: "Guinea", prefix: "3X"},
      %{country: "Guinea Bissau", prefix: "J5"},
      %{country: "Guyana", prefix: "8R"},
      %{country: "Haiti", prefix: "HH"},
      %{country: "Honduras", prefix: "HR"},
      %{country: "Hungary", prefix: "HA"},
      %{country: "Iceland", prefix: "TF"},
      %{country: "India", prefix: "VT"},
      %{country: "Indonesia", prefix: "PK"},
      %{country: "Iran", prefix: "EP"},
      %{country: "Iraq", prefix: "YI"},
      %{country: "Ireland", prefix: "EI"},
      %{country: "Israel", prefix: "4X"},
      %{country: "Italy", prefix: "I"},
      %{country: "Jamaica", prefix: "6Y"},
      %{country: "Japan", prefix: "JA"},
      %{country: "Jersey", prefix: "ZJ"},
      %{country: "Jordan", prefix: "JY"},
      %{country: "Kosovo,Republic of", prefix: "Z6"},
      %{country: "Kazakhstan", prefix: "UP"},
      %{country: "Kenya", prefix: "5Y"},
      %{country: "Kiribati", prefix: "T3"},
      %{country: "Korea,People's Democratic Rep.", prefix: "P"},
      %{country: "Korea,Republic of", prefix: "HL"},
      %{country: "Kuwait", prefix: "9K"},
      %{country: "Kyrgyzstan", prefix: "EX"},
      %{country: "Laos", prefix: "RDPL"},
      %{country: "Latvia", prefix: "YL"},
      %{country: "Lebanon", prefix: "OD"},
      %{country: "Lesotho", prefix: "7P"},
      %{country: "Liberia", prefix: "A8"},
      %{country: "Libya", prefix: "5A"},
      %{country: "Liechtenstein", prefix: "HB"},
      %{country: "Lithuania", prefix: "LY"},
      %{country: "Luxembourg", prefix: "LX"},
      %{country: "Macedonia,Republic of", prefix: "Z3"},
      %{country: "Madagascar", prefix: "5R"},
      %{country: "Malawi", prefix: "7Q"},
      %{country: "Malaysia", prefix: "9M"},
      %{country: "Maldives", prefix: "8Q"},
      %{country: "Mali", prefix: "TZ"},
      %{country: "Malta", prefix: "9H"},
      %{country: "Isle of Man[13]", prefix: "M"},
      %{country: "Marshall Islands", prefix: "V7"},
      %{country: "Mauritania", prefix: "5T"},
      %{country: "Mauritius", prefix: "3B"},
      %{country: "Mexico", prefix: "XA"},
      %{country: "Mexico", prefix: "XB"},
      %{country: "Mexico", prefix: "XC"},
      %{country: "Micronesia,Federated States of", prefix: "V6"},
      %{country: "Moldova", prefix: "ER"},
      %{country: "Monaco", prefix: "3A"},
      %{country: "Mongolia", prefix: "JU"},
      %{country: "Montenegro", prefix: "4O"},
      %{country: "Montserrat", prefix: "VP"},
      %{country: "Morocco", prefix: "CN"},
      %{country: "Mozambique", prefix: "C9"},
      %{country: "Myanmar", prefix: "XY"},
      %{country: "Myanmar", prefix: "XZ"},
      %{country: "Namibia", prefix: "V5"},
      %{country: "Nauru", prefix: "C2"},
      %{country: "Nepal", prefix: "9N"},
      %{country: "Netherlands", prefix: "PH"},
      %{country: "Netherlands Antilles", prefix: "PJ"},
      %{country: "New Zealand", prefix: "ZK"},
      %{country: "Nicaragua", prefix: "YN"},
      %{country: "Niger", prefix: "5U"},
      %{country: "Nigeria", prefix: "5N"},
      %{country: "Norway", prefix: "LN"},
      %{country: "Oman", prefix: "A4O"},
      %{country: "Pakistan", prefix: "AP"},
      %{country: "Pakistan", prefix: "AR"},
      %{country: "Palestine", prefix: "SU"},
      %{country: "Palestine", prefix: "E4"},
      %{country: "Panama", prefix: "HP"},
      %{country: "Papua New Guinea", prefix: "P2"},
      %{country: "Paraguay", prefix: "ZP"},
      %{country: "Peru", prefix: "OB"},
      %{country: "Philippines", prefix: "RP"},
      %{country: "Poland", prefix: "SP"},
      %{country: "Poland", prefix: "SN"},
      %{country: "Portugal", prefix: "CR"},
      %{country: "Portugal", prefix: "CS"},
      %{country: "Qatar", prefix: "A7"},
      %{country: "Raunion Island", prefix: "F"},
      %{country: "Romania", prefix: "YR"},
      %{country: "Russian Federation", prefix: "RA"},
      %{country: "Russian Federation", prefix: "RF"},
      %{country: "Rwanda", prefix: "9XR"},
      %{country: "Saint Helena/Ascension", prefix: "VQ"},
      %{country: "Saint Kitts and Nevis", prefix: "V4"},
      %{country: "Saint Lucia", prefix: "J6"},
      %{country: "Saint Vincent and the Grenadines", prefix: "J8"},
      %{country: "Samoa", prefix: "5W"},
      %{country: "San Marino", prefix: "T7"},
      %{country: "São Tomé and Príncipe", prefix: "S9"},
      %{country: "Saudi Arabia", prefix: "HZ"},
      %{country: "Senegal", prefix: "6V"},
      %{country: "Serbia", prefix: "YU"},
      %{country: "Seychelles", prefix: "S7"},
      %{country: "Sierra Leone", prefix: "9L"},
      %{country: "Singapore", prefix: "9V"},
      %{country: "Slovakia", prefix: "OM"},
      %{country: "Slovenia", prefix: "S5"},
      %{country: "Solomon Islands", prefix: "H4"},
      %{country: "Somalia", prefix: "6O"},
      %{country: "South Africa", prefix: "ZS"},
      %{country: "South Africa", prefix: "ZT"},
      %{country: "South Africa", prefix: "ZU"},
      %{country: "South Sudan", prefix: ""},
      %{country: "Spain", prefix: "EC"},
      %{country: "Sri Lanka", prefix: "4R"},
      %{country: "Sudan", prefix: "ST"},
      %{country: "Surinam", prefix: "PZ"},
      %{country: "Swaziland", prefix: "3D"},
      %{country: "Sweden", prefix: "SE"},
      %{country: "Switzerland", prefix: "HB"},
      %{country: "Syria", prefix: "YK"},
      %{country: "Tajikistan", prefix: "EY"},
      %{country: "Tanzania", prefix: "5H"},
      %{country: "Thailand", prefix: "HS"},
      %{country: "Togo", prefix: "5V"},
      %{country: "Tonga", prefix: "A3"},
      %{country: "Trinidad and Tobago", prefix: "9Y"},
      %{country: "Tunisia", prefix: "TS"},
      %{country: "Turkey", prefix: "TC"},
      %{country: "Turkmenistan", prefix: "EZ"},
      %{country: "Turks and Caicos", prefix: "VQ"},
      %{country: "Tuvalu", prefix: "T2"},
      %{country: "Uganda", prefix: "5X"},
      %{country: "Ukraine", prefix: "UR"},
      %{country: "United Arab Emirates", prefix: "A6"},
      %{country: "United Kingdom", prefix: "G"},
      %{country: "United NationsN3", prefix: "4U"},
      %{country: "United States of America", prefix: "N"},
      %{country: "Uruguay", prefix: "CX"},
      %{country: "Uzbekistan", prefix: "UK"},
      %{country: "Vanuatu", prefix: "YJ"},
      %{country: "Venezuela", prefix: "YV"},
      %{country: "Vietnam", prefix: "VN"},
      %{country: "Yemen", prefix: "7O"},
      %{country: "Zambia", prefix: "9J"},
      %{country: "Zimbabwe", prefix: "Z"},
      %{country: "United Arab Emirates", prefix: "E6"}
    ]
  end
end
